- id: ventialtion level 4
  alias: 'KNX: Set ventilation level to 4 via KNX Switch'
  trigger:
  - platform: event
    event_type: knx_event
    event_data:
      address: 6/1/162
      data: 1
  action:
  - service: modbus.write_register
    data:
      address: 100
      hub: ventilation_unit
      unit: 1
      value: 4
  mode: single
- id: ventialtion level 2
  alias: 'KNX: Set ventilation level to 2 via KNX Switch'
  trigger:
  - platform: event
    event_type: knx_event
    event_data:
      address: 6/1/161
      data: 1
  action:
  - service: modbus.write_register
    data:
      address: 100
      hub: ventilation_unit
      unit: 1
      value: 2
  mode: single
- id: '1588160850545'
  alias: 'Home-Assistant: Update Info'
  description: ''
  trigger:
  - entity_id: binary_sensor.updater
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Update verfügbar! {{ state_attr("binary_sensor.updater", "newest_version")}}
    service: persistent_notification.create
  - data:
      message: Update verfügbar! {{ state_attr("binary_sensor.updater", "newest_version")}}
      title: HA Update
    service: notify.mobile_app_oneplus_a3003
  - service: notify.ha_bot
    data:
      message: Update verfügbar! {{ state_attr("binary_sensor.updater", "newest_version")}}
      title: Home Assistant Update
  mode: single
- id: '1589439603239'
  alias: 'Müllabfuhr: Erinnerung Restmüll'
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ state_attr(''sensor.restmull'', ''remaining'') == 1}}'
  action:
  - data:
      message: Morgen ist Restmüll!
      title: Müllabfuhr
    service: notify.mobile_app_oneplus_a3003
  mode: single
- id: '1593947999011'
  alias: 'Garten: Bewässerung aus nach 2 Stunden'
  description: ''
  trigger:
  - entity_id: switch.brunnenwasserpumpe
    for: 02:00:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Automatisch AUS nach 2 Stunden
      title: Brunnenwasserpumpe
    service: notify.mobile_app_oneplus_a3003
  - data: {}
    entity_id: switch.brunnenwasserpumpe
    service: switch.turn_off
  mode: single
- id: '1602440188705'
  alias: 'Müllabfuhr: Erinnerung Biotonne'
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ state_attr(''sensor.bio_tonne'', ''remaining'') == 1}}'
  action:
  - data:
      message: Morgen ist Biotonne!
      title: Müllabfuhr
    service: notify.mobile_app_oneplus_a3003
  mode: single
- id: '1602440231159'
  alias: 'Müllabfuhr: Erinnerung Gelber Sack'
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ state_attr(''sensor.gelber_sack'', ''remaining'') == 1}}'
  action:
  - data:
      message: Morgen ist Gelber Sack!
      title: Müllabfuhr
    service: notify.mobile_app_oneplus_a3003
  mode: single
- id: '1602440278912'
  alias: 'Müllabfuhr: Erinnerung Blaue Tonne'
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ state_attr(''sensor.blaue_tonne'', ''remaining'') == 1}}'
  action:
  - data:
      message: Morgen ist Blaue Tonne!
      title: Müllabfuhr
    service: notify.mobile_app_oneplus_a3003
  mode: single
- id: '1602440409146'
  alias: 'Lüftungsanlage: Alarm '
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.alarm
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_oneplus_a3003
    data:
      message: Alarm Lüftungsanlage
      title: Alarm Lüftungsanlage
  - service: persistent_notification.create
    data:
      message: Alarm Lüftungsanlage
      title: Alarm Lüftungsanlage
  - service: notify.ha_bot
    data:
      message: Alarm Lüftungsanlage
      title: Alarm Lüftungsanlage
  mode: single
- id: '1604849403561'
  alias: 'Garage: Garagentor Warnung'
  description: ''
  trigger:
  - platform: time
    at: '21:30'
  condition:
  - condition: state
    entity_id: binary_sensor.garagentor_offen
    state: 'on'
  action:
  - service: notify.mobile_app_oneplus_a3003
    data:
      Title: Garage
      Message: Garagentor ist noch offen!
  - service: persistent_notification.create
    data:
      Title: Garage
      Message: Garagentor ist noch offen!
  - service: notify.ha_bot
    data:
      message: Garagentor ist noch offen!
      title: Garage
  mode: single
- id: '1610090635718'
  alias: 'Wallbox: set max current'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.goecharger_max_current
  condition: []
  action:
  - service: goecharger.set_max_current
    data_template:
      max_current: '{{ states(''input_select.goecharger_max_current'') }}'
  mode: single
- id: '1610090775101'
  alias: 'Wallbox: get max current'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.goecharger_024386_charger_max_current
  condition: []
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.goecharger_max_current
      option: '{{ states.sensor.goecharger_024386_charger_max_current.state }}'
    entity_id: input_select.goecharger_max_current
  mode: single
- id: '1610090847300'
  alias: 'Wallbox: set charge limit'
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.goecharger_charge_limit
  condition: []
  action:
  - service: goecharger.set_charge_limit
    data_template:
      charge_limit: '{{ states(''input_number.goecharger_charge_limit'') }}'
  mode: single
- id: '1610090921931'
  alias: 'Wallbox: get charge Limit'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.goecharger_024386_charge_limit
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.goecharger_charge_limit
      value: '{{ states.sensor.goecharger_024386_charge_limit.state }}'
    entity_id: input_number.goecharger_charge_limit
  mode: single
- id: '1614062167163'
  alias: 'Corona: Neue Zahlen'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.corona_wt_active
  condition: []
  action:
  - service: notify.ha_bot
    data:
      title: Neue Corona Zahlen
      message: Um {{ "%02d:%02d" % (now().hour, now().minute) }} gab es neue Corona
        Zahlen!
  mode: single
- id: '1614192808850'
  alias: 'Wallbox: Ladeende Info'
  description: Schickt die Kosten und Lademenge der letten Ladung nachdem diese beendet
    wurde
  trigger:
  - platform: state
    entity_id: sensor.goecharger_024386_car_status
    from: charging
  condition: []
  action:
  - service: notify.ha_bot
    data:
      title: eNiro laden beendet
      message: Es wurden {{ states('sensor.goecharger_024386_current_session_charged_energy')
        }}kWh geladen, dies hat {{ "%0.3f" % (states('sensor.energy_cost_standard')|float
        *states('sensor.goecharger_024386_current_session_charged_energy') | float
        ) | float}}€ gekostet ({{ states('sensor.energy_cost_standard') }}€/kwh)
  mode: single
- id: '1614623279187'
  alias: 'Wallbox: Ladestart info'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.goecharger_024386_car_status
    to: charging
  condition: []
  action:
  - service: notify.ha_bot
    data:
      title: eNiro laden gestartet
      message: Laden gestartet um {{ now().hour }}:{{ now().minute }}
  mode: single
- id: '1626067681110'
  alias: SwissHydroApi Check
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '5'
  condition:
  - condition: template
    value_template: '''{{ as_timestamp(now()) - as_timestamp(states.sensor.rhine_level.last_changed)
      > 600 }}'''
  action:
  - service: notify.mobile_app_oneplus_a3003
    data:
      message: SwissHydroApi Stale
      title: 'Warning: SwissHydroApi'
  mode: single
