version: "3"

services:

  caddy:
    container_name: caddy
    image: custom-caddy
    build: /opt/docker/webserver/caddy
    env_file:
      - /opt/docker/webserver/caddy/caddy.env
    volumes:
      - /opt/docker/webserver/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/webserver/caddy/data:/data
      - /opt/docker/webserver/caddy/config:/config
      - /opt/docker/webserver/www:/www
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - webserver

networks:
  webserver:
    name: webserver
    driver: bridge
