- name: "Terrasse"
  address: "1/1/170"
  state_address: "1/4/170"

- name: "Haustüre"
  address: "1/1/180"
  state_address: "1/4/180"

- name: "Garage"
  address: "1/1/200"
  state_address: "1/4/200"

