- name: "Flur UG"
  address: "1/1/130"
  state_address: "1/4/130"

- name: "Kleiner Keller"
  address: "1/1/140"
  state_address: "1/4/140"

- name: "Großer Keller"
  address: "1/1/150"
  state_address: "1/4/150"

- name: "Technikraum"
  address: "1/1/160"
  state_address: "1/4/160"

