- address: 
  - "6/1/130" # Taster Terrasse: Licht Komplett 
  - "6/1/131" # Taster Terrasse: Licht Hälfte
  - "6/1/132" # Taster Terrasse: Sprinkler Automatik
  - "6/1/133" # Taster Terrasse: Tropfleitung
  - "6/1/134" # Taster Terrasse: Rasenmäher Roboter


