- name: Brunnenwasserpumpe
  address: '6/1/160'
  state_address: '6/4/160'

- name: Bewässerung Kreis 1
  address: '6/2/1'
  state_address: '6/3/1'

- name: Bewässerung Kreis 2
  address: '6/2/2'
  state_address: '6/3/2'

- name: Bewässerung Kreis 3
  address: '6/2/3'
  state_address: '6/3/3'

- name: Bewässerung Kreis 4
  address: '6/2/4'
  state_address: '6/3/4'

- name: Bewässerung Kreis 5
  address: '6/2/5'
  state_address: '6/3/5'

- name: Bewässerung Kreis 6
  address: '6/2/6'
  state_address: '6/3/6'

