version: "3"

services:
  homer:
    container_name: homer
    image: b4bz/homer
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /opt/docker/internal/homer:/www/assets
    restart: unless-stopped
    networks:
      - webserver
      - internal
    depends_on:
      - caddy

  paperless-redis:
    container_name: paperless-redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /opt/docker/internal/paperless/redis:/data
    networks:
      - internal

  paperless-gotenberg:
    container_name: paperless-gotenberg
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - internal

  paperless-tika:
    container_name: paperless-tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    networks:
      - internal

  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /storage/paperless/data:/usr/src/paperless/data
      - /storage/paperless/media:/usr/src/paperless/media
      - /storage/paperless/export:/usr/src/paperless/export
      - /storage/paperless/consume:/usr/src/paperless/consume
    env_file: paperless.env
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_EMAIL_TASK_CRON: "*/1 * * * *"
    networks:
      - webserver
      - internal

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - immich-redis
      - immich-postgres
      - immich-typesense
    restart: always
    networks:
      - internal
      - webserver

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - immich-redis
      - immich-postgres
      - immich-typesense
    restart: always
    networks:
      - internal

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /opt/docker/internal/immich/model-cache:/cache
    env_file:
      - /opt/docker/internal/.env
    restart: always
    networks:
      - internal

  immich-typesense:
    container_name: immich-typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /opt/docker/internal/immich/typesense:/data
    restart: always
    networks:
      - internal

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:3995fe6ea6a619313e31046bd3c8643f9e70f8f2b294ff82659d409b47d06abb
    restart: always
    networks:
      - internal

  immich-postgres:
    container_name: immich-postgres
    image: postgres:14-alpine@sha256:874f566dd512d79cf74f59754833e869ae76ece96716d153b0fa3e64aec88d92
    env_file:
      - /opt/docker/internal/.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/docker/internal/immich/db/:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

networks:
  internal:
    name: internal
